language: java

sudo: false

addons:
  sonarcloud:
    organization: "salgokrisz-github"
    token:
      secure: "$SONAR_TOKEN"

before_script: cd Cluedo



jobs:

  include:

    - stage: compile

      script: mvn compile

    - stage: sonar
    
      script: mvn org.jacoco:jacoco-maven-plugin:prepare-agent verify sonar:sonar -DskipTests=true -Dmaven.test.failure.ignore=true
<<<<<<< HEAD

=======
      
>>>>>>> 81443d7d247d8c737a749c24796211d9dbbddf36
    - stage: test

      script: mvn test

stages:

  - compile
  
  - sonar

  - test 
  

