language: java

sudo: false

addons:
  sonarcloud:
    organization: "bence762-github"
    token:
      secure: "$SONAR_TOKEN"

jdk:
    -oraclejdk8

before_script: cd Cluedo



jobs:

  include:

    - stage: compile

      script: mvn compile

    - stage: sonar
    
      script: mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar

    - stage: test

      script: mvn test

stages:

  - compile
  
  - sonar

  - test 
  

