language: java

sudo: false

addons:
  sonarcloud:
    organization: "salgokrisz-github"
    token:
      secure: "$SONAR_TOKEN"

before_script: cd Cluedo



jobs:

  include:

    - stage: compile

      script: mvn compile

    - stage: sonar
    
      script: sonar-scanner
      
    - stage: test

      script: mvn test

stages:

  - compile
  
  - sonar

  - test 
  

