language: java
sudo: false
before_script: cd Cluedo

jobs:
    include:
        stage: "Unit test"
        script: mvn clean verify
        stage: "Deploy"
        script: echo "not yet implemented"

