language: java

sudo: false

addons:
  sonarcloud:
    organization: "salgokrisz-github"
    token:
      secure: "$SONAR_TOKEN"

before_script: cd Cluedo



jobs:

  include:

    - stage: compile

      script: mvn compile
    
    - stage: pmd
    
      script: mvn pmd:pmd -f text

    - stage: sonar
    
      script: mvn org.jacoco:jacoco-maven-plugin:prepare-agent verify sonar:sonar -DskipTests=true -Dmaven.test.failure.ignore=true

    - stage: test

      script: mvn test

stages:

  - compile
  
  - pmd
  
  - sonar

  - test 
  

