language: java

sudo: false

addons:
  sonarcloud:
    organization: "salgokrisz-github"
    token:
      secure: "$SONAR_TOKEN"
      
before_script: cd Cluedo

jobs:

  include:

    - stage: compile

      script: mvn compile
      
    - stage: test

      script: mvn test
      
    - stage: pmd and coverage(Emma)
    
      script: 
             - mvn compile site
             - mvn pmd:pmd
             - mvn verify

    - stage: sonar    
    
      script: mvn org.jacoco:jacoco-maven-plugin:prepare-agent verify sonar:sonar -DskipTests=true -Dmaven.test.failure.ignore=true

stages:

  - compile

  - test
  
  - pmd and coverage(Emma)
  
  - sonar

  

