language: java
sudo: false
before_script: cd Cluedo

jobs:
  include:
    - stage: compile
      script: mvn compile
    - stage: test
      script: mvn test
    - stage: deploy
      script: mvn deploy
stages:
  - compile
  - test
  - name: deploy
    if: branch = master
         

