language: java

sudo: false

addons:
  sonarcloud:
    organization: "salgokrisz-github"
    token:
      secure: "$SONAR_TOKEN"
      
before_script: cd Cluedo

jobs:

  include:

    - stage: compile

      script: mvn compile
      
    - stage: test

      script: mvn test
      
    - stage: pmd
    
      script: 
             - mvn compile site
             - mvn pmd:pmd
             - mvn verify

    - stage: sonar    
    
      script: mvn org.jacoco:jacoco-maven-plugin:prepare-agent verify sonar:sonar -DskipTests=true -Dmaven.test.failure.ignore=true
    
    - stage: deploy
    
      script: skip
      deploy:
            provider: releases
            user: "salgokrisz"
            password:
              secure: ErdsBhpu1Dw+x5dFPC8km76jqwZoVp5Lv5yCQAQiLODHcspI6ifbZvPWJ0EjHA7Rr2yajYnaSPd4bqb4iL0lq6rJujH6bWXSIazvVt7xMvmR95akmoTgOEf+rMhEw0QYjwnM7u3AUxUuM0cRJx3xKpFYumfyoh04UFwhwbGl835mjX5NUgpLgzNDVStfHWJwFEi/WhGTkPBJUAKF1ihWa4MaZIJ1pMAbMxl+dkR9vOSxQYVtGRTvSensVP3FE+ytjXQHa0H2V6kLjwUVlvhxNxiNsISrVX6TdFUDm7uS70wrl1V5AvtY/V6rmgCfDXqfdgJcNjDED9Mngn4Q0OX1NJoKiOfHvpLtC6BiOFYSZJLiYT9Bz2SuojfjEKJvVQhagruQE4W3cZ48GheK7MbFvpXacEhtn2hDEF0Sruk+gjYscQWdB90I0uC+cFkQFeC25izKNY4HcQslf3CK0IFazvmLn5OCJFdTgK98R4vdwK9KlNm8Itg3VFeYdJUX+rnjhbKYhlbLO5DeqxmpW8oPKEvy/gdebtT+bbqlyprMJIt93YNaagkq9bGbRXkhsdeH0xueHMNoDghv7h59jgb4EEW0BiXJly8uQBEeEfl6pAcnHZIpi4b0VWfe/aO6v//ho/uSwoHBjhGdF/AM+Btmp4M4L0C04pOn2nCk7LpLxV4=
            file: "Cluedo-1.0-SNAPSHOT-spring-boot.jar"
            skip_cleanup: true
            on:
              branch: master

stages:

  - compile

  - test
  
  - pmd
  
  - sonar
  
  - deploy

  

