language: java

sudo: false

addons:
  sonarcloud:
    organization: "salgokrisz-github"
    token:
      secure: "$SONAR_TOKEN"
      
before_script: cd Cluedo

jobs:

  include:

    - stage: compile

      script: mvn compile
      
    - stage: test

      script: mvn test
      
    - stage: pmd
    
      script: 
             - mvn compile site
             - mvn pmd:pmd
             - mvn verify

    - stage: sonar    
    
      script: mvn org.jacoco:jacoco-maven-plugin:prepare-agent verify sonar:sonar -DskipTests=true -Dmaven.test.failure.ignore=true
    
    - stage: deploy
    
      script: skip
                 
      deploy:
            provider: releases
            api_key: "8e8972d189a7c1e84fc5cfb343bd6436ee643326"
            file: "Cluedo.jar"
            skip_cleanup: true
            on:
               branch: master

stages:

  - compile

  - test
  
  - pmd
  
  - sonar
  
  - deploy

  

