language: java
sudo: false
before_script: cd Cluedo

jobs:
    include:
        stage: "Unit test"
        script:./FieldFactoryTest.java
        stage: "Deploy"
        script: echo "not yet implemented"

